# Generated by Django 3.1.2 on 2020-10-09 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Categori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Movie', to='Movie.category'),
        ),
    ]
