# Generated by Django 3.1.2 on 2020-10-15 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0005_auto_20201014_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Rate',
        ),
    ]
